Vanilla james chatroom folders
beoble/beoble-toolkit pull request #317
Opened 2023-04-12 02:03 UTC by vanilla-james

2023-04-12 07:38 UTC, bamnenim-kryptonium requested changes

2023-04-12 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Icon/Icon.tsx
> +  stroke: string;
better to make this as optional param

2023-04-12 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Icon/Icon.tsx
> +      stroke={stroke ?? ''}
this can be optional param in above

2023-04-12 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Icon/Icon.tsx
>        {icon === 'MetaMask' && <MetaMaskSvg />}
It's better to make a function to check icon type with else/if or switch case.
Current code will run and check all the conditions here

2023-04-12 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/types/types.ts
> +export type TextColor = 'main' | 'secondary' | 'beobleRed' | 'initial';
Which color type are u referring here?
I think it's better to use it from theme by theme provider or from color palette

2023-04-12 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/hooks/useBottomFooterNav.ts
> +import { shouldShowBottomNav } from '../consts/routes';
Just noticed this function earlier but i think this should be under helper or util folder instead of being under the consts folder (const should stand only for the constants)

2023-04-12 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/hooks/useRouteAndRouterMeta.ts
> +  const [windowLocationPathname, setWindowLocationPathname] = useState('');
If this hook would be used in multiple places, this will cause multiple-state instance generation.

It's better to register the event to the next/router with the atom as global state at the initialization step (like useApp that will be called one time for life cycle)

2023-04-12 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/hooks/useRouteAndRouterMeta.ts
> +  const currentRoutePathname = useMemo(() => {
feel like this is just router.pathname - why do we need this separately?

2023-04-12 07:38 UTC, bamnenim-kryptonium commented on packages/example/next.config.js
> +    styledComponents: true,
is this a new requirement for next 13?

2023-04-12 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Button/Button.tsx
> -      iconPosition={buttonMeta[buttonType]?.iconPosition || 'left'}
these values are all 'default value' and it's better to be located in the component parameter field

2023-04-12 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Button/Button.tsx
>    backgroundColor?: string;
default values here

2023-04-12 07:43 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Icon/Icon.tsx
> +  stroke: string;
yup def

2023-04-12 07:44 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Icon/Icon.tsx
>        {icon === 'MetaMask' && <MetaMaskSvg />}
good point - 
will find a better way
just didn't want to make the Svg component into a Dynamic component like I did last time
- cause I thought the usage of Dynamic components was pretty confusing and hard to maintain in the long run

2023-04-12 07:45 UTC, vanilla-james commented on packages/beoble/components/DesktopView/types/types.ts
> +export type TextColor = 'main' | 'secondary' | 'beobleRed' | 'initial';
will use the theming
I have been bad at re-using the theming stuff

2023-04-12 07:45 UTC, vanilla-james commented on packages/beoble/hooks/useBottomFooterNav.ts
> +import { shouldShowBottomNav } from '../consts/routes';
yup, will combine into the bottom footer related hook

2023-04-12 07:46 UTC, vanilla-james commented on packages/beoble/hooks/useRouteAndRouterMeta.ts
> +  const [windowLocationPathname, setWindowLocationPathname] = useState('');
I added this into a separate hook so that the next router could be prevented from being imported in multiple files
will keep your point in mind and fix

2023-04-12 07:47 UTC, vanilla-james commented on packages/beoble/hooks/useRouteAndRouterMeta.ts
> +  const currentRoutePathname = useMemo(() => {
I added this into a separate hook so that the next router could be prevented from being imported in multiple files
will keep your point in mind and fix

2023-04-12 07:47 UTC, vanilla-james commented on packages/example/next.config.js
> +    styledComponents: true,
yup, this is to prevent the mis match between the server and client re: the dynamic className that StyledComponent generates

2023-04-12 07:48 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Button/Button.tsx
> -      iconPosition={buttonMeta[buttonType]?.iconPosition || 'left'}
yup will clean up default values - thought I had done so but missed some

2023-04-12 09:53 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Button/Button.tsx
> +          size={buttonMeta[buttonType]?.size || 'md'}
removing these in lieu of Icon component default props as well

2023-04-13 19:03 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Button/Button.tsx
> -      iconPosition={buttonMeta[buttonType]?.iconPosition || 'left'}
per your guidance I switched over to using default param values within the StyledComponent - good catch

2023-04-13 19:10 UTC, vanilla-james commented on packages/beoble/components/DesktopView/types/types.ts
> +export type TextColor = 'main' | 'secondary' | 'beobleRed' | 'initial';
check again - I think this code should be good to go as I am limiting the text color of Buttons using the type above, and then checking against the condition to show the correct color from `ColorPalette` in
> packages/beoble/styles/colors.ts

```
  ${({ textColor = 'initial' }) => {
    switch (textColor) {
      case 'main':
        return `color: ${ColorPalette.primary};`;
      case 'secondary':
        return `color: ${ColorPalette.secondary};`;
      case 'beobleRed':
        return `color: ${ColorPalette.beobleRed};`;
      case 'initial':
        return 'color: initial;';
    }
  }}
```

2023-04-13 19:38 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Icon/Icon.tsx
>        {icon === 'MetaMask' && <MetaMaskSvg />}
resolved using lazy to dynamically load the svgs with a Suspense boundary
good point about the performance

the fixed way will only load the relevant svg (was loading all svgs in the Icon file, in addition to your point about checking whether to show every svg as you pointed out)

2023-04-14 01:57 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/types/types.ts
> +export type TextColor = 'main' | 'secondary' | 'beobleRed' | 'initial';
what is the primary and secondary color you are referring to here?
If it is the theme's primary and secondary color, you should use provided 'theme' prop + align the names with it
(and even warning color can be located in the theme if we want)

``` javascript
  ${({ theme, textColor = 'initial' }) => {
    switch (textColor) {
      case 'primary':
        return `color: ${theme.primary};`;
      case 'secondary':
        return `color: ${theme.secondary};`;
      case 'warn':
        return `color: ${ColorPalette.beobleRed};`;
      case 'initial':
        return 'color: initial;';
    }
  }}
```

2023-04-14 04:08 UTC, vanilla-james commented on packages/beoble/components/DesktopView/types/types.ts
> +export type TextColor = 'main' | 'secondary' | 'beobleRed' | 'initial';
ah, I used `ColorPalette` to specify the colors by referencing your previous commit:

https://github.com/beoble/beoble-toolkit/blob/e9dd10857897f8efd3a0a08249d164724e589e79/packages/beoble/components/DesktopView/Button/Button.tsx

```
LOGIN: {
    icon: 'MetaMask',
    text: 'Connect Wallet',
    backgroundColor: ColorPalette.beoblePine,
  },
  NEW_CHAT: {
    backgroundColor: 'black',
    icon: 'Plus',
    text: 'New chat',
  },
  CHATROOM_INFO: {
    text: 'See chatroom settings',
    icon: 'Info',
  },
  LEAVE_CHATROOM: {
    text: 'Leave group',
    icon: 'Trash can',
    textColor: 'beobleRed',
  },
};

const StyledButton = styled.button<{
  backgroundColor?: string;
  iconPosition?: IconPosition;
  hasExtraPadding?: boolean;
  hasOutline?: boolean;
  isRounded?: boolean;
  textColor?: TextColor;
  size?: ButtonSize;
  isSelected: boolean;
  customText: string;
}>`
  /* 
    NOTE: set 2px border as transparent, then add 2px border for
    hover, outline etc.
    box-sizing: border-box; should do the trick without this,
    but I have currently not been able to get it to work as expected.
  */
  border: 2px solid transparent;
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: ${({ customText }) => (customText ? '700' : '500')};

  ${({ size }) => {
    switch (size) {
      case 'small':
        return css`
          font-size: 12px;
          padding: 4px 4px;
          border-radius: 4px;
        `;
      case 'medium':
        return css`
          font-size: 16px;
          padding: 8px 8px;
          border-radius: 12px;
        `;
      case 'large':
        return css`
          font-size: 16px;
          padding: 16px 16px;
          border-radius: 12px;
        `;
    }
  }}

  ${({ textColor }) => {
    switch (textColor) {
      case 'main':
        return 'color: #7067cf;';
      case 'secondary':
        return 'color: #0fbbef;';
      case 'beobleRed':
        return 'color: #e71f64;';
      case 'initial':
        return 'color: initial;';
    }
  }}

  ${({ backgroundColor }) => {
    switch (backgroundColor) {
      case 'black':
        return css`
          background-color: #1c1c1b;
          color: #ffffff;
        `;
      case 'white':
        return css`
          background-color: #ffffff;
          color: #1e1e1e;
        `;
      case 'none':
        return 'background-color: transparent;';
      default:
        return css`
          background-color: ${backgroundColor};
          color: ${ColorPalette.light};
        `;
    }
  }}
```

but I will utilize `theme` as you pointed out 🤗

2023-04-14 04:15 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/types/types.ts
> +export type TextColor = 'main' | 'secondary' | 'beobleRed' | 'initial';
Color palette is for saving the constant value of our colors.
Theme is a set of aligning colors in the same theme.

So Color palette is actually being used in Theme.

2023-04-14 04:24 UTC, vanilla-james commented on packages/beoble/components/DesktopView/types/types.ts
> +export type TextColor = 'main' | 'secondary' | 'beobleRed' | 'initial';
also there are two places where our colors are defined:

> packages/react/src/theme/Colors.ts

> packages/beoble/styles/colors.ts

and since per our recent discussion, files that should be shared between web and mobile etc. should be in our `react` package, we should gradually refactor to exclusively use colors from 
> packages/react/src/theme/Colors.ts

will refactor some styles during this PR

2023-04-14 04:26 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/types/types.ts
> +export type TextColor = 'main' | 'secondary' | 'beobleRed' | 'initial';
Yeap that is perfect. But I think it's better to be in a different task

2023-04-14 04:34 UTC, vanilla-james commented on packages/beoble/components/DesktopView/types/types.ts
> +export type TextColor = 'main' | 'secondary' | 'beobleRed' | 'initial';
ok changed, this part
will refactor other ColorPalette styles to use theme styles later when we refactor
(many values need to be added to the theme etc.)

2023-04-14 04:42 UTC, vanilla-james commented on packages/beoble/hooks/useRouteAndRouterMeta.ts
> +  const [windowLocationPathname, setWindowLocationPathname] = useState('');
relocated this and code from comment below into the component that needs the logic
> packages/beoble/components/global/Footer/BottomNavFooter.tsx

and deleted the hook
> packages/beoble/hooks/useRouteAndRouterMeta.ts

(abstracting these functions into hook was probably overkill similar to what you mentioned)

2023-04-14 04:42 UTC, vanilla-james commented on packages/beoble/hooks/useRouteAndRouterMeta.ts
> +  const currentRoutePathname = useMemo(() => {
https://github.com/beoble/beoble-toolkit/pull/317#discussion_r1166270794

2023-04-14 05:51 UTC, bamnenim-kryptonium approved these changes

2023-04-14 06:02 UTC, merged

2023-04-14 06:15 UTC, bamnenim-kryptonium approved these changes