alpha-explore-and-more
beoble/beoble-toolkit pull request #356
Opened 2023-05-31 11:06 UTC by vanilla-james

2023-06-07 07:38 UTC, bamnenim-kryptonium requested changes

2023-06-07 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Profile/ProfileCard/ProfileCard.tsx
> +      if ((profile as Follower).wallet?.address) {
https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates
use type predicates (type assertion can be dangerous)
e.g) `if(isFollower(profile)) return profile.wallet.address;`

2023-06-07 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Profile/ProfileCard/ProfileCard.tsx
> +    type === 'ForYouLeaderboard' ? (profile as IUser).wallets[0] : ''
if profile is Follower / Following i think than is line will throw error since wallets attribute does't exist in those?

2023-06-07 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Profile/ProfileCard/ProfileCard.tsx
Toom any type assertions

2023-06-07 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/LensFollowersProfiles.tsx
> +  const { hasLensFollowersAndFollowingProfiles } =
combine useLensFollowersAndFollowingProfilesAtom hook as one

2023-06-07 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/ProfileCardsCarousel.tsx
>    const columnVirtualizer = useVirtualizer({
are we using two different virtual scroll libraries in our app?

This is quite embarrassing. we should keep only one library for the same feature.
need to discuss enough and decide which one should go to before using a library like this.

2023-06-07 07:38 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/ProfileCardsCarousel.tsx
> +                  onClick={() => {
if onClick does nothing, we can just omit it i think?

2023-06-14 08:26 UTC, vanilla-james commented on packages/react/src/hooks/useUserAndProfileValues.ts
> +    idToCheck: string | undefined;
I think its better to keep this because the return object should always have an `idToCheck` regardless of the id being a user id or wallet address.

and if `undefined` the corresponding query will not trigger (will not be enabled) in the code below

```

  const { data: userDataByUniqueParam, isLoading } = useGetUserByUniqueParam(
    userDataInQueryClient ? '' : userUniqueParamMeta.idToCheck,
    userUniqueParamMeta.uniqueParam,
    createIfNotExists
  );
```

2023-06-14 08:28 UTC, vanilla-james commented on packages/react/src/hooks/useUserAndProfileValues.ts
> +        idToCheck: userId,
ok - need to train my brain more to use nullish coalescing
I also liked to split up the conditions with `if`s just in case in the future the nested code gets more complicated, but changed to nullish coalescing as you commented

2023-06-14 08:29 UTC, vanilla-james commented on packages/react/src/hooks/useUserAndProfileValues.ts
> +export const useUserAndProfileValues = (
yes, good point, best to keep the function call signature simple
will do

2023-06-14 08:29 UTC, vanilla-james commented on packages/beoble/components/Organisms/PanelPages/ProfilePage.tsx
> +    ''
this is extension of the above

2023-06-14 08:32 UTC, vanilla-james commented on packages/react/src/atoms/useLensFollowersAndFollowingProfilesAtom.ts
The structure started out this way because
1. if a user does not have Lens followers
2. the Leaderboard profile cards, which are at the bottom of the Explore page, come to the top of the page, when the user does not have Lens followers

I implemented this using `order: 1 | 3` in a `display: flex`, where the order is conditionally assigned based on the above conditions.

Will check if I am simplify / if the logic has changed when I first implemented to remove use of atom if possible.

2023-06-14 08:33 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Profile/ProfileCard/ProfileCard.tsx
> +            : nonBreakingSpace()}
agree
just figuring out what I should name the value
```
export const NON_BREAKING_SPACE = '\u00A0';
```
etc.

and if this will normal with the JSX markup
```
<DisplayName>{displayName || NON_BREAKING_SPACE}</DisplayName>
```

🤔

2023-06-14 08:33 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Profile/ProfileCard/ProfileCard.tsx
> +const StyledProfileCardContainer = styled.div<{
will review and implement

2023-06-14 08:35 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Profile/ProfileCard/ProfileCard.tsx
> +      if ((profile as Follower).wallet?.address) {
yeah as you pointed out def too many assertions
will use a better way
type narrowing, merge discriminated union, etc. etc.

2023-06-14 08:36 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/ProfileCardsCarousel.tsx
>    const columnVirtualizer = useVirtualizer({
yes embarrassing...
will move over to `react-virtuoso` after alpha launch as we finally agreed?

2023-06-14 08:38 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/ProfileCardsCarousel.tsx
> +                  onClick={() => {
yes, I should've
but then I changed the `onClick`
> packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/ProfileCardsCarousel.tsx
to required
so I will pass in a void function

For components that can be expected to have a click functionality (button, icon, card, avatar etc.)
I think it will be good to make `onClick` required, then explicitly void the click function for components that aren't clickable, while also having typescript remind us to pass in a click action for (I would guess) most clickable components that should have a click action

2023-06-14 09:21 UTC, vanilla-james commented on packages/react/src/hooks/useUserAndProfileValues.ts
> +        idToCheck: userId,
Using the proposed way is surfacing a bug.
(simply, a user can be requested using their user id or wallet address, and because user data is only requested if user data by **user id or wallet address** does not exist, and because the proposed way does not take this into consideration, the bug summarized below is surfacing)

if I change to
```
return {
      idToCheck: walletAddress ?? userId,
      uniqueParam: walletAddress ? 'wallet_address' : 'user_id',
}
```
it works, but since the original way is safer given the current code state, I will leave as is

--------
👇 **A bit hard to explain, but the current bug that exists related to getting user data is as follows:**

I was working on it in a previous branch, but right now when a user logs in
the first time they login, a request is made to get user data that returns an "empty" user from the backend.

I have narrowed it down to this call in 
> packages/react/src/atoms/useApp.ts

```
  useTruthy(() => {
    fetchUser(ethers.utils.getAddress(account.address!));
  }, [account.address]);
```

which fetches a user not using react-query, but the previous way.

1. removing this query prevents the "empty" user being returned from the backend
2. BUT removing this query creates bugs when the browser is refreshed after a user logs in

so it wasn't a simple removal that solves the case.

anyways, long winded explanation

I was trying to look into:
1. removing all GET user queries that do not use react-query
2. using [persistQueryClient](https://tanstack.com/query/v4/docs/react/plugins/persistQueryClient) to persist the data upon refresh

but then got busy again with the Explore page.

I will keep the above code as it is, as it is more "safe" given the current state of our code, but we need to eventually remove user (and other endpoint resources) requests that do not use react query as it is cause non synchronized server state (and possibly other issues) in our codebase.

**TL;DR**
we need to fix all user requests to use react-query or so will be user data bugs (user data synchronization issues) here and there in the codebase

2023-06-15 08:47 UTC, vanilla-james commented on packages/react/src/hooks/useUserAndProfileValues.ts
> +export const useUserAndProfileValues = (
will refactor in next working branch
as it is used in more than 30 files

will manage with this Jira:
https://kryptonium.atlassian.net/browse/BEOBLE-1648

2023-06-15 09:12 UTC, vanilla-james commented on packages/react/src/atoms/useLensFollowersAndFollowingProfilesAtom.ts
reviewed this

I didn't reuse the Lens React hooks because there is no simple way to disable / dedupe them without additional custom logic

These are the hooks that I am using to get Lens followers and following.
```
import {
  useProfile,
  useProfilesOwnedBy,
  useProfileFollowers,
  useProfileFollowing,
} from '@lens-protocol/react-web';
```

The current atom usage is a good way to share the necessary, data, loading etc. states where the values are needed.

2023-06-15 11:00 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useLensFollowersAndFollowingProfilesAtom.ts
In this case, u can delay the point where the required data will be used by separating the hooks.
```ts
import {
  Profile,
  useProfileFollowers,
  useProfileFollowing,
} from '@lens-protocol/react-web';
import { useMemo } from 'react';

export const useLensFollowingAndFollowers = (
  profile: Profile,
  walletAddress: string
) => {
  const { data: followers, loading: followerLoading } = useProfileFollowers({
    profileId: profile.id,
  });
  const { data: followings, loading: followingLoading } = useProfileFollowing({
    walletAddress,
  });

  const loading = useMemo(
    () => followerLoading || followingLoading,
    [followerLoading, followingLoading]
  );

  const data = useMemo(
    () => [...(followers ?? []), ...(followings ?? [])],
    [followers, followings]
  );

  return { loading, data };
};

```

and use this with in the component

```ts
export const LensFollowerAndFollowings = (
  profile: Profile,
  walletAddress: string
) => {
  const { loading, data } = useLensFollowingAndFollowers(
    profile,
    walletAddress
  );

  return (
    <>
      {data.map((profile) => (
        // return with data
        <></>
      ))}
    </>
  );
};
```

and render this component only when the required data is usable.


```ts
const test = () => {
  const { loggedInUser } = useUserAndProfileValues();
  const { data: profilesOwnedByData, loading: profilesOwnedByLoading } =
    useProfilesOwnedBy({
      address: loggedInUser?.wallets?.at(0) || '',
      // address: '0xe83a60B49bc01F8bEF8D9CA9b0d197443b0e4dAF', // sung
      // address: '0xd0b13457F264664A59B869F3bc477bfB7Fe42A4F', // nft.sushi
      // address: '0xb033fB14cF7Dc769488Ad34Ae90D4b3AD810BB25', // jungwoo
    });

  if (profilesOwnedByData?.[0] && loggedInUser) return (
    <LensFollowerAndFollowings
      profile={profilesOwnedByData?.[0]}
      walletAddress={loggedInUser.wallets[0]}
    />
  );
  return <></>;
};
```

2023-06-15 11:42 UTC, vanilla-james commented on packages/react/src/atoms/useLensFollowersAndFollowingProfilesAtom.ts
1. the approach I took gives importance to getting all the Lens follower and following data in serial and ASAP
because the Explore page layout will shift the screen / swap with the Leaderboard profiles
(at least before we add nice skeleton loading screens with nice predetermined heights for the skeletons to match the profile cards and carousel)
depending on whether a user has 
a. a lens account
b. followers and following attached to that account

not sure if your way incurs any delays (just cause you mention delay in your comment - I think you might just mean delay the point of component / code organization) but we want to minimize any delays as much as possible

2. also to reiterate my initial comment reply, because I don't want to trigger multiple calls to the `useProfileFollowers` and `useProfileFollowing` functions, which are now in `useLensFollowingAndFollowers`
I think it is just better to call in one place and reuse the data

I am currently using the atom to re-use the state and data in
> packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/LeaderboardProfiles.tsx
> packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/LeaderboardProfiles.tsx
so that would already be 2 * 2 calls as opposed to just 2 calls if I were to use a hook like useLensFollowingAndFollowers

(and I would also need to additionally call the `useProfile` and `useProfilesOwnedBy` in all the components needing the state and data, which adds even more Lens React hook requests)

The Lens React hook endpoints are free, but want to minimize requests just in case they add a non-free APi cost

I also originally thought about wrapping the Lens React hooks in custom hooks, decided against that route just to keep the code a bit simpler

will take a deeper look and compare
might have missed some things about your approach and my approach so let's meet back here if anything important comes up

2023-06-15 16:28 UTC, bamnenim-kryptonium requested changes

2023-06-15 16:28 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/queries/chatroom/useSearchPuiblicChatRoom.ts
> +  limit?: number
default value should be here

2023-06-15 16:28 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useUserAndProfileValues.ts
> +    idToCheck: string | undefined;
if you ensure `idToCheck` will have value: remove undefined type.
if the value can be undefined: using optional parameter or explicit undefined type will have same effect.

2023-06-15 16:28 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useUserAndProfileValues.ts
> +        idToCheck: userId,
If this behaves differently it will be mainly because of the difference between nullish coalescing and if statement.
Nullish coalescing will only assinreturns its right-hand side operand when its left-hand side operand is [null](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/null) or [undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined), while if statement will pass if the value is falsy

So that means in somewhere it's passing empty string instead of undefined for the userId or wwalletAddress.

I think we should not accept passing empty string for both parameters and use nullish  coalescing

2023-06-15 16:28 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useUserAndProfileValues.ts
> +    return userDataByID || userDataByWallet || userDataByUniqueParam;
add userDataByUniqueParam to deps?

2023-06-15 16:28 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/User/UserListItem/UserListItemFirstRow.tsx
> +import { getLevelInfo } from '../../../../../react/src/components/Tissues/Level/config';
export it in @beoble/react package if it not being imported properly,
and import it from '@beoble/react'

2023-06-15 16:28 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/User/UserListItem/UserListItemSecondRow.tsx
> +import { getLevelInfo } from '../../../../../react/src/components/Tissues/Level/config';
same here!

2023-06-15 16:28 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab.tsx
> +    handle: profilesOwnedByData?.at(0)?.handle as string,
already mentioned in this [thread](https://github.com/beoble/beoble-toolkit/pull/356/files/6556ef60c1251dff7e407944492089ffbdf8ae59)

But again, using type assertion like this is bad practice.

2023-06-16 03:49 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/LeaderboardProfiles.tsx
>              ...(communityRankingsData.user_with_top_followers.at(0) as IUser),
it was because I was initializing profiles as empty array
but will remove initialization

2023-06-16 04:03 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/LeaderboardProfiles.tsx
>              ...(communityRankingsData.user_with_top_followers.at(0) as IUser),
actually I need to initialize as empty array so that profiles behaves as an array
(I am immutably spreading new values into profiles)
without the initialization TypeScript throws never[] related error
(similar to commonly seen error when useState is used without a proper type definition)

2023-06-16 05:27 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/ProfileCardsCarousel.tsx
> +const ChevronLeftContainer = styled.div<{ shouldShowLeftChevron: boolean }>`
removed duplication
used visibility so that left and right chevron occupy space in the dom within their flexbox layout
so that when showing and being hidden their positions don't shift

2023-06-16 05:27 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/LeaderboardProfiles.tsx
>              ...(communityRankingsData.user_with_top_followers.at(0) as IUser),
I mean for the line 36 `...(communityRankingsData.user_with_top_followers.at(0) as IUser),`
here

2023-06-16 05:27 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Explore/Tabs/Web3CommunityChat/ChatroomListItem/ChatroomListItem.tsx
> +type ChatroomListItemType = Extract<ExploreTabOptions, 'Web3 community chat'>;
because there are 3 `ExploreTabOptions`
```
export type ExploreTabOptions =
  | 'For you'
  | 'Web3 community chat'
  | 'Leaderboard';
```

and in the future the chatroom list item can be used for the other tab types
right now there is only 1 implementation type but I wanted to be flexible for the future

also even though it's just 1 value
I am extracting it from a single source of truth of options so that type `Web3 community chat` isn't a magic string / just randomly assigned as a string type (this could introduce type typo etc. bugs)

2023-06-16 05:28 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Explore/Tabs/Web3CommunityChat/ChatroomListItem/ChatroomListItem.tsx
> +      chatroomSearchResult?.official_chatroom_type.includes('REGION') ||
types added here:

> packages/js-sdk/src/lib/types/chatroom.ts:69
```
export type OfficialChatRoomType =
  | 'TAG'
  | 'LANGUAGE'
  | 'REGION'
  | 'NON_FUNGIBLE_TOKEN'
  | 'FUNGIBLE_TOKEN'
  | 'NATIVE_COIN';
```

2023-06-16 05:28 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Explore/Tabs/Web3CommunityChat/ChatroomListItem/ChatroomListItemButton.tsx
> +  type: Extract<ExploreTabOptions, 'Web3 community chat'>;
same reason as above
to futureproof for more types and prevent string type typos

2023-06-16 05:28 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Explore/Tabs/Web3CommunityChat/ChatroomSearch.tsx
>    let debounced;
cool - done

2023-06-16 05:29 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Profile/ProfileCard/ProfileCard.tsx
> +    push('PROFILE', { id: userData?.at(0)?.id ?? '' });
good point
added a generic error toast for now if there is no id
similar unexpected error conditions should be thought out and a designed error toast should be added for later

2023-06-16 05:30 UTC, vanilla-james commented on packages/js-sdk/src/lib/Requests/chatroom.ts
> +export type OfficialChatroomLanguage =
The values in the type array are some of the possible values returned from the backend
https://dev.api.beoble.app/v1/docs/openapi/redoc#operation/_search_public_chatroom_v1_search_chatroom_public_get

I thought it would be good to define all the possible `official_chatroom_value` types (there are more possible types that needed to be added after check redoc etc. docs), which I thought would be good to check response data in the frontend as needed

but if it is unnecessary / prohibitively difficult to define all the possible types backend is sending we can remove

2023-06-16 05:30 UTC, vanilla-james commented on packages/react/src/hooks/queries/chatroom/useSearchPuiblicChatRoom.ts
> +  limit?: number
that is the right way - done

2023-06-16 05:31 UTC, vanilla-james commented on packages/react/src/hooks/useUserAndProfileValues.ts
> +    return userDataByID || userDataByWallet || userDataByUniqueParam;
> add userDataByUniqueParam to deps?
ah linter is fickle about this - sometimes it shows and other times it doesn't

for the other 
> packages/react/src/hooks/useUserAndProfileValues.ts
changes, I feel more comfortable doing it in a separate branch
as more changes related to removing useUserAtom etc. should be done together to clean this up in the best way

2023-06-16 05:31 UTC, vanilla-james commented on packages/beoble/components/DesktopView/User/UserListItem/UserListItemFirstRow.tsx
> +import { getLevelInfo } from '../../../../../react/src/components/Tissues/Level/config';
done

2023-06-16 05:31 UTC, vanilla-james commented on packages/beoble/components/DesktopView/User/UserListItem/UserListItemSecondRow.tsx
> +import { getLevelInfo } from '../../../../../react/src/components/Tissues/Level/config';
and done

2023-06-16 05:31 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab.tsx
> +    handle: profilesOwnedByData?.at(0)?.handle as string,
yup will remove all previous type assertions as I get to them

2023-06-16 05:59 UTC, vanilla-james commented on packages/beoble/components/DesktopView/Explore/Tabs/ForYouTab/LeaderboardProfiles.tsx
>              ...(communityRankingsData.user_with_top_followers.at(0) as IUser),
ah removed these asertions
not sure why but spreading the value directly has a type error vs. putting the value into a const first is preventing type errors

2023-06-19 16:18 UTC, vanilla-james commented on packages/react/src/atoms/useLensFollowersAndFollowingProfilesAtom.ts
> 1. the call stack is just the same as what you implemented. It shouldn't behave differently from the current one.

checking the Network tab in the browser (and even the graphql specific [GraphQL Network Inspector](https://chrome.google.com/webstore/detail/graphql-network-inspector/ndlbedplllcgconngcnfmkadhokfaaln?hl=en-GB) browser plugin) it appears that there are no additional requests

however, when calling the function multiple times, the data that the Lens React hook (in the example below `useProfileFollowing`, but this happens for `useProfileFollowers` as well) returns accumulates the data of multiple requests, this is very weird again because the Network and GraphQL Network Inspector tabs do not show extra requests, nor do they show any mutated data from the first request

---
✅ single request
```
  const { data } = useProfileFollowing({
    walletAddress: '0xd0b13457F264664A59B869F3bc477bfB7Fe42A4F', // nft.sushi
    limit: 10,
  });

  console.log('data: ', data); 
```

=> returns 10 followings as expected
<img width="652" alt="image" src="https://github.com/beoble/beoble-toolkit/assets/6829451/937fe110-b38f-4c5a-9c9c-44dac1bc2521">

=> and 1 graphql fetch request in Network tab
<img width="657" alt="image" src="https://github.com/beoble/beoble-toolkit/assets/6829451/f85880fe-4e29-46c0-bfd0-12055f603698">

=> and also in GraphQL Network Inspector tab
<img width="657" alt="image" src="https://github.com/beoble/beoble-toolkit/assets/6829451/ad22b0f0-d171-43b8-9052-26b9fc07934c">

---
❌ multiple requests
(two requests are made in a row to simplify the example, but the same behavior happens when calling the Lens React hooks in multiple files/components)

```

  const { data } = useProfileFollowing({
    walletAddress: '0xd0b13457F264664A59B869F3bc477bfB7Fe42A4F', // nft.sushi
    limit: 10,
  });

  console.log('data: ', data);

  const { data: data2 } = useProfileFollowing({
    walletAddress: '0xd0b13457F264664A59B869F3bc477bfB7Fe42A4F', // nft.sushi
    limit: 10,
  });

  console.log('data2: ', data2);

```
=> the first and second responses to the hooks,`data` and `data2`, respectively, return 20 followings, which is twice as many as expected and not the behavior we want
<img width="639" alt="image" src="https://github.com/beoble/beoble-toolkit/assets/6829451/76ec8a50-801e-4abb-9afc-7e5fef33fee1">

even though the Network tab and GraphQL Network Inspector tab only show 1 request as in the ✅ single request case

as you can assume, 3 requests is returning 40, 4 requests is returning 80 ... and on and on

for now, since I already need multiple requests, I don't think we can rely on the Lens React hooks implementation without storing the fetched data separately

---

> 2. lens data is persistent as stated in [document](https://docs.lens.xyz/docs/sdk-react-intro). Also, I have tested in our app that it doesn't fire any network with the same parameters on re-render. (You can think it works the same as react-query)

I missed the point about data fetching being de-deuplicated by the Lens React hooks
the link mentions Persistence

> Persistence
> The SDK takes care of storing relevant informations for subsequent user sessions. It comes with out-of-the box adapters for common storage providers and will enable developers to define the storage provider solution that works best for their application needs.

which would help commonly share data from different components in our app, but I couldn't find info on preventing excessive data fetches etc. and based on the above, it appears that relying on the Lens React hooks to persist and share data, it will not be the correct data that we want to display in the UI

2023-06-20 11:16 UTC, bamnenim-kryptonium approved these changes

2023-06-20 11:16 UTC, merged