[WiP] - Local db
beoble/beoble-toolkit pull request #359
Opened 2023-06-05 10:28 UTC by Phillemono

2023-06-06 02:59 UTC, bamnenim-kryptonium requested changes

2023-06-06 02:59 UTC, bamnenim-kryptonium commented on packages/beoble/components/Chat/index.tsx
> +        return prevState.cloneWithRows(messagesRef.current as any);
why did u add typecasting with any here?

2023-06-06 02:59 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useLocalMessages.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
avoid using explicit any as possible.

2023-06-06 02:59 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useLocalMessages.ts
> +  const checkDuplicateArrays = (array1: any, array2: any, property: any) => {
this function can be moved to array utill or helper folders.
and suggest to use 'any[]' type for array

2023-06-06 02:59 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useLocalMessages.ts
> +  const checkDuplicateArrays = (array1: any, array2: any, property: any) => {
and property can be string

2023-06-06 02:59 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useLocalMessages.ts
> +  const concatMessages = useCallback(
let's move this to helper function folder
since it's not doing anything with states

2023-06-06 02:59 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useLocalMessages.ts
> +  const areMessagesStored = async (messageIds: string[]): Promise<string[]> => {
1. why do we need to wrap it with try-catch? what is the potential error we can get?
2. the function started with are/is should return boolean value

2023-06-06 02:59 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useLocalMessages.ts
> +    setPage(1);
shouldn't we reset messages when chatroom is changed?
why it's not setting up set mesage sent?

2023-06-06 02:59 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useChannel.ts
> +          chatroomId,
we should use same casing for storing obj
camel case vs snake case
seems like we are storing chatroomId with camel case and created_at with snake case?

2023-06-06 02:59 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useChannel.ts
> +          isDummy: false,
casing issue here too?

2023-06-06 02:59 UTC, bamnenim-kryptonium commented on packages/beoble/pages/_app.tsx
> +  const db = new PouchDB('messages');
can u move these pouch db providers into provider/Provider.tsx

2023-06-06 18:21 UTC, Phillemono commented on packages/react/src/hooks/useLocalMessages.ts
> +    setPage(1);
we do setting message as undefined

2023-06-28 06:27 UTC, bamnenim-kryptonium requested changes

2023-06-28 06:27 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useChatRoom.ts
> +  const getChatroom = async () => {
this one should work as it was by changing query to interact with memory not from the local DB directly.

2023-06-28 06:27 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useLocalMessages.ts
> +  const updateDoc = useCallback(async (data: any, confirm_id?: string) => {
we can have better name like updateMessages (to make more clear to know if we see this in outside)

2023-06-28 07:01 UTC, Phillemono commented on packages/react/src/hooks/local-db/useLocalChatrooms.ts
> +    }
Its better to be memoizing cuz if the chatrooms returns the same values

2023-06-28 07:08 UTC, Phillemono commented on packages/react/src/hooks/local-db/useLocalChatrooms.ts
> +  }, []);
No need to add them i guess

2023-06-28 10:09 UTC, bamnenim-kryptonium approved these changes

2023-06-28 10:09 UTC, merged