Messages list fixes
beoble/beoble-toolkit pull request #377
Opened 2023-07-11 16:46 UTC by Phillemono

2023-07-12 09:09 UTC, vanilla-james commented on packages/beoble/components/global/Overlay.tsx
> +  align-items: center;
keep the flex related properties together so they can be determined in one glance?

2023-07-12 09:10 UTC, vanilla-james commented on packages/beoble/components/global/Overlay.tsx
> +  max-height: 90%;
what is the significance of `90%` for these two values?

2023-07-12 09:14 UTC, vanilla-james commented on packages/beoble/pages/index.tsx
> +import { AiOutlineExclamationCircle } from 'react-icons/ai';
the Toast related markup has been updated to re-use our toast component in my other PR
https://github.com/beoble/beoble-toolkit/pull/378

2023-07-12 09:19 UTC, vanilla-james commented on packages/react/src/components/Message/index.tsx
> +                <ReactionsContainer {...{ contentType }}>
same as above

2023-07-12 09:20 UTC, vanilla-james commented on packages/react/src/hooks/useChannel.ts
> +    // resetMessages();
delete if no longer necessary

2023-07-13 09:41 UTC, vanilla-james commented
updating this working branch with the latest origin dev branch 
because I didn't merge my previous PR to dev

2023-07-13 09:42 UTC, vanilla-james commented on packages/beoble/components/global/Overlay.tsx
>  const OverlayImage = styled.img`
use next/image when possible
for image optimizations

2023-07-17 19:34 UTC, Phillemono commented on packages/beoble/components/global/Overlay.tsx
> +  max-height: 90%;
Making sure it doesn't pass across the screen , cuz sometimes images ratio are different

2023-07-18 05:35 UTC, bamnenim-kryptonium requested changes

2023-07-18 05:35 UTC, bamnenim-kryptonium commented on packages/js-sdk/src/core/notification.ts
> +  public retrieveMessage(
I think this function is quite redundant.
we can just add boolean parameter to decide whether to retrieve new messages or old messages

2023-07-18 05:35 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useNotificationAtom.ts
> +    setTimeout(() => {
why did u add set time out here?

2023-07-18 05:35 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useNotificationAtom.ts
> +  }, []);
I think we need to provide proper dependencies. (in this case, chatSound, user, addNewChat)

2023-07-18 05:35 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useNotificationAtom.ts
> +  const handleNewChatroom = (data: NotiResponseType) => {
we can wrap following two handle functions with useCallback too

2023-07-18 05:35 UTC, bamnenim-kryptonium commented on packages/react/src/components/Message/index.tsx
I will replace this with new component. lmk if u find any inconsistency after!

2023-07-18 05:35 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useChannel.ts
> +    setPrivateKey('');
better to set it as undefined to express we don't have the value

2023-07-18 05:35 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useChannel.ts
I will remove messagesToProps and all the related converting logic since our new chat component only need IChat.
I might ask u some help while applying!

2023-07-18 05:35 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useChatRoom.ts
> +    console.warn(chatroom?.is_encrypted, user, Beoble.auth.authToken);
remove log

2023-07-18 05:35 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useChatRoom.ts
> +  }, [chatroom, chatroom_id, Beoble.auth.authToken, user]);
useTruthy hook will only be executed if all the dependencies are truthy value.

2023-07-18 09:56 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useNotificationAtom.ts
> +  }, []);
add handleOpenChatroom and handleCreateChatroom into dependency list

2023-07-18 09:56 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useNotificationAtom.ts
> +  }, []);
add rotuer as dependency

2023-07-18 14:22 UTC, bamnenim-kryptonium approved these changes

2023-07-18 14:22 UTC, merged