BEOBLE-1754: adding-members-to-pre-existing-chatrooms-not-working-properly
beoble/beoble-toolkit pull request #383
Opened 2023-07-18 13:26 UTC by vanilla-james

2023-07-20 12:06 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatHeaderEllipsisButtonsBundle.tsx
> +    leave.mutate({
i think we should not call the mutation if chatRoomId doesn't exist

2023-07-20 12:07 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatroomInfoEllipsisButtonsBundle.tsx
> +    leave.mutate({
same here

2023-07-20 12:10 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatroomMemberActionButtonsBundle.tsx
> +export default function ChatroomMemberActionButtonsBundle({
i feel like the name is a bit unmatched. Isn't this just a button with a dropdown?
Hence we can later abstract this button with drop-down component separately. 

lastly, plz us named export

2023-07-20 12:13 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/User/UserListItem.tsx
> +      return userData?.at(0)?.wallets?.[0];
u don't need optional chaining here since it's already checked in the condition state

2023-07-20 12:13 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/User/UserListItem/UserListItemFirstRow.tsx
> +      ? utils.truncateString(userDataToShow?.wallets?.[0] ?? '', 20, 6, 6)
same here, don't need optional chaining since it is already checked in the condition

2023-07-20 12:17 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCard.tsx
can you move this under @beoble/components/Organs/ContractCard?

2023-07-20 12:25 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCard.tsx
> +  const { userProfileRepresentativeMedia, userIsOnline } =
i think we don't need this part since IMember already has user inside in it.

2023-07-20 12:28 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCard.tsx
> +  const { isDirectChat, isUserChannelOwner } = useChatroomValues(
member has chatroom_role fieldd
![image](https://github.com/beoble/beoble-toolkit/assets/95412790/e8bcba44-0522-488c-8be5-e423495d284e)

2023-07-20 12:32 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCard.tsx
> +        <ChatRoomInfoContractCardButton
I think it's better to decide which component should be passed in `buttonOverride` in this component rather than having another component only for this.

2023-07-20 12:33 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCard.tsx
> +  const { isDirectChat, isUserChannelOwner } = useChatroomValues(
also as i understand we don't need bifurcation for direct chat, so i think we can remove this `useChatroomValues` hook

2023-07-20 12:34 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCard.tsx
> +  const contractCardButtonType = useMemo(() => {
control which component to put in `buttonOverride` here directly.

2023-07-20 12:34 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCard.tsx
> +export default function ChatRoomInfoMember({ member }: { member: IMember }) {
use named export

2023-07-20 12:34 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCardButton.tsx
remove this component

2023-07-20 12:35 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCardDropdown.tsx
> +export default function ChatRoomInfoContractCardDropdown({
use named export

2023-07-20 12:36 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCardDropdown.tsx
> +    <DropdownMenu.Root>
you can wrap this with one more div to add ` onClick={(e) => {
            e.stopPropagation();
          }}`

2023-07-20 12:37 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoMembers.tsx
👍 now can u move this component to organ system folder

2023-07-20 14:01 UTC, vanilla-james commented on packages/react/src/components/Tissues/ContractCard/index.stories.tsx
> +  avatar: testUser.wallets?.[0],
These are occurring because I marked the `wallets` and `display_name` properties in the User type as optional
(I changed these types because I was getting runtime errors from non optional changed values).

> packages/js-sdk/src/lib/Models/user.ts

The related optional chaining changes are required due to this type change.
I will revert changing the User type properties to optional as I think it requires making too many of these changes.

The User type can be updated at a later time and fixed.

2023-07-20 14:08 UTC, vanilla-james commented on packages/react/src/hooks/queries/chatroom/useGetChatroomMembers.ts
> +    chatRoomId: string,
same as from above:  I think that `enabled: !!chatRoomId,` is better to handle whether the query is run or not with additional logic

2023-07-20 14:11 UTC, vanilla-james commented on packages/react/src/atoms/useUserAtom.ts
> +      user!.wallets?.[0] ?? '',
again related to updating the User type

packages/js-sdk/src/lib/Models/user.ts

will revert

2023-07-20 14:12 UTC, vanilla-james commented on packages/react/src/atoms/useNotificationAtom.ts
> +            !Beoble.auth.checkAuthTokenValidity(user.wallets?.[0])
related to updating the User type

packages/js-sdk/src/lib/Models/user.ts

will revert

2023-07-20 14:14 UTC, vanilla-james commented on packages/beoble/components/Profile/ProfileWalletDetails.tsx
> +    copy(viewedUserData?.[0].wallets?.[0] ?? '');
related to updating the User type

packages/js-sdk/src/lib/Models/user.ts

will revert

2023-07-20 14:15 UTC, vanilla-james commented on packages/beoble/components/DesktopView/User/UserListItem.tsx
> +      return userData?.at(0)?.wallets?.[0];
related to updating the User type

packages/js-sdk/src/lib/Models/user.ts

will revert

2023-07-20 14:16 UTC, vanilla-james commented on packages/beoble/components/DesktopView/User/UserListItem/UserListItemFirstRow.tsx
> +      ? utils.truncateString(userDataToShow?.wallets?.[0] ?? '', 20, 6, 6)
related to updating the User type

packages/js-sdk/src/lib/Models/user.ts

will revert

2023-07-20 14:22 UTC, vanilla-james commented on packages/react/src/components/CreateChatPanel/index.tsx
> +    chatroom?.id ?? ''
same as above
I think it's better to make the params needed to build the get query as required
and let the `enabled` flag process whether the query is run or not
while also maintaining the ability to make subsequent params required

ref: https://github.com/beoble/beoble-toolkit/pull/383#discussion_r1269517193

2023-07-20 14:23 UTC, vanilla-james commented on packages/beoble/components/Organs/ContractCards/UserContractCard/index.tsx
> +      ? utils.truncateString(user.wallets?.[0], 10, 5, 4)
related to updating the User type

packages/js-sdk/src/lib/Models/user.ts

will revert

2023-07-20 14:23 UTC, vanilla-james commented on packages/beoble/components/Organisms/PanelPages/Chat/CreateDefaultGroupChatPage.tsx
> +    chatroom?.id ?? ''
same as above
I think it's better to make the params needed to build the get query as required
and let the enabled flag process whether the query is run or not
while also maintaining the ability to make subsequent params required

ref: https://github.com/beoble/beoble-toolkit/pull/383#discussion_r1269517193

2023-07-20 14:36 UTC, vanilla-james commented on packages/react/src/components/UserListItem/index.tsx
will do

2023-07-20 14:36 UTC, bamnenim-kryptonium commented on packages/react/src/components/Tissues/ContractCard/index.stories.tsx
> +  avatar: testUser.wallets?.[0],
The change is the correct way. You should not revert this.
I'm giving you guides on how to deal with undefined wallet cases.
(apply to all same issues)

2023-07-20 14:38 UTC, vanilla-james commented on packages/react/src/hooks/mutations/chatroom/usePutChatroomMembers.ts
noted!

2023-07-20 14:39 UTC, vanilla-james commented on packages/beoble/helper/filterStrings.ts
> +      console.log(
ah I got `debug` and `useDebug` confused, will use `debug` 👍

2023-07-20 14:41 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/queries/chatroom/useGetChatroomMembers.ts
> +  chatRoomId: string,
1. I'm suggesting this way because i saw several cases that passing or handling undefined chatroom_id in higher components/hooks. Even though empty string works the same as undefined (falsy value), that leads unnecessary handling in higher place and even i saw some bad practice like forcing type with `as`. I've changed some queries that deal with undefined parameter before, so i would want to ask you to follow this implementation.

2. limit is already an optional parameter with the default value.

2023-07-20 14:49 UTC, vanilla-james commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatroomMemberActionButtonsBundle.tsx
> +export default function ChatroomMemberActionButtonsBundle({
all files in the `ButtonsBundles` have the potential to be more than one button

![image](https://github.com/beoble/beoble-toolkit/assets/6829451/8b8511b3-b32a-47c6-9e14-c3f1a322b5ff)

specifically in the case of chatroom info member dropdown, the dropdown currently only includes `remove member` but later needs to include more buttons such as `make admin` etc.

converted to name export

2023-07-20 14:52 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatroomMemberActionButtonsBundle.tsx
> +export default function ChatroomMemberActionButtonsBundle({
Understood but i think better to abstract the level of components to dropdown.
Is there any case that these bundles are going to be used in some where else than in dropdown?

2023-07-20 14:53 UTC, vanilla-james commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCard.tsx
> +  const { userProfileRepresentativeMedia, userIsOnline } =
not sure why but the member.user objects being returned have no profile

will inquire to backend

2023-07-20 17:28 UTC, bamnenim-kryptonium requested changes

2023-07-20 17:28 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatHeaderEllipsisButtonsBundle.tsx
> +  const { chatRoomId, openChat } = usePanelRouter();
can u change chatRoomId in `usePanelRouter` to be type `string | undefined` like this?
``` typescript
const chatroomId = useMemo(() => {
  if (Array.isArray(query.id)) return query.id[0];
  else return query.id;
}, [query.id]);
```

2023-07-20 17:28 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatHeaderEllipsisButtonsBundle.tsx
>    const { leaveChatroomText } = useChatroomValues(chatRoomId as string);
do not use type assertion here

2023-07-20 17:28 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatHeaderEllipsisButtonsBundle.tsx
> +      chatroomId: typeof chatRoomId === 'string' ? chatRoomId : '',
if we change chatroomId to have type `string | undefined`, we can just use chatRoomId directly

2023-07-20 17:28 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatroomInfoEllipsisButtonsBundle.tsx
Same comment with the above one

2023-07-20 17:28 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatroomInfoEllipsisButtonsBundle.tsx
> +        openChat(typeof chatRoomId === 'string' ? chatRoomId : '');
this can be shorten with applying the above change

2023-07-20 17:28 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatroomMemberActionButtonsBundle.tsx
> +          onClick={() => {
think u can just use `handleAdminPopoverItemClick ` without function notation

2023-07-20 17:28 UTC, bamnenim-kryptonium commented on packages/beoble/components/FilterSettings/ChatRoom/ChatRoomInfoContractCard.tsx
👍  👍  👍

2023-07-20 17:28 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useUserAtom.ts
``` typescript
const register = async (user_id: string, onRegister?: () => void) => {
  if (!user || !user.wallets?.[0]) throw new Error('user should be fetchted first!');
  const res = await Beoble.updatePublicKey(
    user?.id ?? user_id,
    user.wallets?.[0],
    undefined,
    signMessageAsync
  );
  /* */
}
```

2023-07-20 17:28 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useNotificationAtom.ts
> +            userAddress: user.wallets?.[0],
```typescript
  const openNotification = async () => {
    // ensure user has at least one wallet here
    if (user && user.wallets?.[0] && !notification && Beoble.auth.authToken) { 
      const noti = Beoble.notification(user.id);
      noti.on('open', () => {
        debug(`notification opened with ${user.id}, in dapp ${Beoble.app_id}`);
        intervalId.current = setInterval(() => {
          noti.ping();
        }, 1000);
        const openMessage: IFrameMessage = {
          type: 'USER_NOTIFICATION_OPENED',
          data: {
            userId: user.id,
            dappId: Beoble.app_id,
            userAddress: user.wallets[0]
          },
        };
  // more...
```

2023-07-20 17:28 UTC, bamnenim-kryptonium commented on packages/beoble/hooks/useSignIn.ts
```typescript
  const retreiveInjectedAccount = async (user: IUser) => {
   if(!user.wallets?.[0]) throw new Error("user should have at least 1 wallet") // add this line
    setConnectingState((prev) => {
      return { ...prev, status: 'INJECTING_ACCOUNT' };
    });
    if (!user.public_key) {
      return await register(user.id, () => {
        router.push('/profile/edit?isUserOnboarding=true');
      });
    } else {
      const injected = await Beoble.getInjectedAccount(
        user.wallets[0],
        signMessageAsync
      );
      return injected;
    }
  };
```

2023-07-21 05:14 UTC, bamnenim-kryptonium requested changes

2023-07-21 05:14 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatroomMemberActionButtonsBundle.tsx
> +      chatroomId: typeof query.id === 'string' ? query.id : '',
we can use chatRoomId from usePanelRouter now?

2023-07-21 05:14 UTC, bamnenim-kryptonium commented on packages/beoble/hooks/useSignIn.ts
> +        user.wallets[0] ?? '',
we can now remove this user.wallets[0] undefined handling

2023-07-21 05:14 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useNotificationAtom.ts
> +            userAddress: user.wallets?.[0],
we can use `user.wallets[0]` since we checked the value exist above

2023-07-21 05:14 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useNotificationAtom.ts
> +            !Beoble.auth.checkAuthTokenValidity(user.wallets?.[0])
we can use `user.wallets[0]` since we checked the value exist above

2023-07-21 05:14 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useUserAtom.ts
> +      user!.wallets[0] ?? '',
we can use `user.wallets[0]` since we checked the value exist above

2023-07-21 05:22 UTC, bamnenim-kryptonium approved these changes

2023-07-21 06:33 UTC, bamnenim-kryptonium requested changes

2023-07-21 06:33 UTC, bamnenim-kryptonium commented on packages/beoble/hooks/usePanelRouter.ts
> +    if (Array.isArray(router.query.id)) return router.query.id.at(0) ?? '';
It's better to return `undefined` explicitly for non-existing value

2023-07-21 06:46 UTC, bamnenim-kryptonium requested changes

2023-07-21 06:46 UTC, bamnenim-kryptonium commented on packages/beoble/components/DesktopView/DropdownWithButtons/ButtonsBundles/ChatHeaderEllipsisButtonsBundle.tsx
> -              id: chatRoomId as string,
think we should prevent to push if chatRoomId is falsy value

2023-07-21 06:46 UTC, bamnenim-kryptonium commented on packages/beoble/hooks/usePanelRouter.ts
> +    return router.query.id ?? '';
here to return undefined if not exist ( just remove ?? '')

2023-07-21 07:24 UTC, bamnenim-kryptonium approved these changes

2023-07-21 07:32 UTC, merged