Fixed opening chats so fast
beoble/beoble-toolkit pull request #385
Opened 2023-07-23 10:15 UTC by Phillemono

2023-07-31 06:56 UTC, Phillemono commented
Fixed bugs: 
1 - [Chatroom breaks clicking too fast](https://www.notion.so/beoble/952280c4197a46e8a1af560220ae1e60?v=00cca914212b439090a91e2fe851a597&p=66ef1660cbb4438190865328f9b57696&pm=s)
2 - [media disappearance](https://www.notion.so/beoble/952280c4197a46e8a1af560220ae1e60?v=00cca914212b439090a91e2fe851a597&p=09714d8cf45047b4985f82054bf69471&pm=s)
3 - [Mark as read](https://www.notion.so/beoble/952280c4197a46e8a1af560220ae1e60?v=00cca914212b439090a91e2fe851a597&p=1bc9ed2539694f069b8cf5365d2d228b&pm=s)
4 - [Sticker disappearance](https://www.notion.so/beoble/952280c4197a46e8a1af560220ae1e60?v=00cca914212b439090a91e2fe851a597&p=09714d8cf45047b4985f82054bf69471&pm=s)
5 - [Chatroom with few messages loading forever](https://www.notion.so/beoble/952280c4197a46e8a1af560220ae1e60?v=00cca914212b439090a91e2fe851a597&p=2cc91410408441258adad1f2f50a7f13&pm=s)

2023-07-31 07:15 UTC, vanilla-james commented on packages/beoble/components/Chat/index.tsx
> +        {!hasNoMessages && messages && messages?.length > 50 ? (
can `!hasNoMessages` and `messages` be combined into one state property?
doesn't `messages` being defined imply `!hasNoMessages` or is the state too complicated?

2023-07-31 07:15 UTC, vanilla-james commented on packages/react/src/atoms/useIsGlobalLoading.ts
> +const isChatroomLoadingAtom = atom(false);
`isChatroomLoading` and related state and logic shouldn't be in 
> useIsGlobalLoading.ts ?

create a separate state / file?

2023-07-31 07:15 UTC, vanilla-james commented on packages/react/src/atoms/useNotificationAtom.ts
> +  const [notificationListener, setNotificationListenerLoading] = useAtom(
just curious
when is it better in an atom to use `useState` vs. `useAtom`?

2023-07-31 07:15 UTC, vanilla-james commented on packages/react/src/components/Message/index.tsx
> +          loading="eager"
Next recommends using the `priority` Image prop to eagerly load messages
https://nextjs.org/docs/pages/api-reference/components/image#loading

Is this a use case where `loading="eager"` is necessary?

2023-07-31 07:53 UTC, Phillemono commented on packages/react/src/components/Message/index.tsx
> +          loading="eager"
Thanks will look at that

2023-07-31 07:54 UTC, Phillemono commented on packages/react/src/atoms/useNotificationAtom.ts
> +  const [notificationListener, setNotificationListenerLoading] = useAtom(
Using useAtom to hold the state during the app lifecycle

2023-07-31 09:21 UTC, vanilla-james requested changes

2023-07-31 09:21 UTC, vanilla-james commented on packages/react/src/atoms/useIsGlobalLoading.ts
> -
add linebreak back to prevent unnecessary diff in this file

2023-07-31 09:21 UTC, vanilla-james commented on packages/beoble/components/Chat/index.tsx
> +        {!hasNoMessages && messages && messages?.length > 50 ? (
updates on this comment?

2023-07-31 09:21 UTC, vanilla-james commented on packages/react/src/hooks/client/useChatRoomClient.ts
> +    const queryString = window.location.search;
is this a different value from 
`chatRoomId` in 
> packages/beoble/hooks/usePanelRouter.ts

if its the same value, you should use `chatRoomId` from usePanelRouter

2023-07-31 19:27 UTC, bamnenim-kryptonium requested changes

2023-07-31 19:27 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/client/useChatRoomClient.ts
this is not allowed fix.

do not use external state to modify client hook.
The hook should be pure to mange the client with chatroom state only.
 (in this case, do not use useUserAtom and next's Router)
 
 plz fix in different way

2023-07-31 19:27 UTC, bamnenim-kryptonium commented on packages/react/src/hooks/useChannel.ts
> -      setTimeout(() => {
just curious, why did u use timeout before?

2023-07-31 19:27 UTC, bamnenim-kryptonium commented on packages/react/src/atoms/useNotificationAtom.ts
>      return () => {
Can u explain why did you add this loading state to add event listeners?

plus i have made huge changes in both useChannel and useNotificationAtom with refactoring.
Can you take a look on that

2023-07-31 23:05 UTC, Phillemono commented on packages/react/src/hooks/useChannel.ts
> -      setTimeout(() => {
To prevent the hook from updating so fast, if the user tried to change the chatrooms frequently but i changed that

2023-07-31 23:08 UTC, Phillemono commented on packages/react/src/hooks/client/useChatRoomClient.ts
Actually i don't use the (useUserAtom or next's Router) i am using the query params, did you mean we should handle it in a different way?

2023-07-31 23:13 UTC, Phillemono commented on packages/react/src/hooks/client/useChatRoomClient.ts
> +    const queryString = window.location.search;
Nope, its not a different value, but i guess we can't use usePanelRouter in client hooks

2023-07-31 23:16 UTC, Phillemono commented on packages/react/src/atoms/useNotificationAtom.ts
>      return () => {
I added the loading states to make sure that the notification socket not to trigger the listener multiple times, cuz it used to trigger it every time we initialize the useChannel hook

2023-08-01 04:38 UTC, vanilla-james requested changes

2023-08-01 04:38 UTC, vanilla-james commented on packages/react/src/hooks/client/useChatRoomClient.ts
> +    const queryString = window.location.search;
wouldn't it work if you call
`usePanelRouter` in the body of the useChatRoomClient hook and not in this function

2023-08-01 10:06 UTC, vanilla-james requested changes

2023-08-01 10:06 UTC, vanilla-james commented on packages/beoble/components/Organisms/PanelPages/Home.tsx
>                      onClick={() => {
if onClick only responds when
`if (!isChatroomLoading)`
then either display an error or disable click action when the condition is not met

2023-08-01 10:06 UTC, vanilla-james commented on packages/react/src/atoms/useChatroomLoading.ts
> + */
delete

2023-08-03 08:23 UTC, bamnenim-kryptonium approved these changes

2023-08-03 08:23 UTC, merged