Added try and catch to prevent random socket error
beoble/beoble-toolkit pull request #392
Opened 2023-08-03 20:49 UTC by Phillemono

2023-08-03 20:51 UTC, Phillemono commented
1 - https://www.notion.so/beoble/952280c4197a46e8a1af560220ae1e60?v=00cca914212b439090a91e2fe851a597&p=c26039f19cc341f4a100d5b1a451f6fc&pm=s

2 - https://www.notion.so/beoble/952280c4197a46e8a1af560220ae1e60?v=00cca914212b439090a91e2fe851a597&p=55c74238e13740f98ce4a1df0b56e913&pm=s

2023-08-04 04:22 UTC, vanilla-james requested changes

2023-08-04 04:22 UTC, vanilla-james commented on packages/js-sdk/src/core/notification.ts
> +      const data = this.isEncrypted ? this.encryptMessage(message) : message;
if this.isEncrypted
shouldn't it call a function named
this.`decryptMessage`(message)?

2023-08-04 04:22 UTC, vanilla-james commented on packages/js-sdk/src/core/notification.ts
> +      console.log(error);
no console logs

2023-08-04 04:22 UTC, vanilla-james commented on packages/js-sdk/src/core/notification.ts
> +      console.log(error);
no console logs

2023-08-04 04:22 UTC, vanilla-james commented on packages/js-sdk/src/core/notification.ts
> +      console.log(error);
no console logs

2023-08-04 04:22 UTC, vanilla-james commented on packages/js-sdk/src/core/notification.ts
> +      console.log(error);
no console logs

2023-08-04 04:22 UTC, vanilla-james commented on packages/js-sdk/src/core/notification.ts
> +      console.log(error);
no console logs

for client if beneficial to user show in info toast
for server if better to catch in a different file, throw an appropriate error

2023-08-04 09:35 UTC, Phillemono commented on packages/js-sdk/src/core/notification.ts
> +      console.log(error);
There would be no way to show info toast, in our SDK, and these kind of logs, is just added to prevent to catch just to make sure it doesn't crash the app should we remove the logs here it could be empty

2023-08-04 09:37 UTC, bamnenim-kryptonium commented on packages/js-sdk/src/core/notification.ts
> +      const data = this.isEncrypted ? this.encryptMessage(message) : message;
if it is encrypted channel, encrypt message when sending a meesage

2023-08-04 10:02 UTC, bamnenim-kryptonium approved these changes

2023-08-04 10:03 UTC, merged