BEOBLE-1813 feat: initial commit
beoble/beoble-toolkit pull request #396
Opened 2023-08-08 06:01 UTC by chanhyeokryptonium

2023-08-17 05:02 UTC, chanhyeokryptonium commented on packages/plugin/package.json
> +    "build-plugin": "sh ./commands/build-plugin.sh",
TODO: rollback

2023-08-17 05:39 UTC, chanhyeokryptonium commented on packages/react/src/components/Cells/Svg/Icons/Lock.tsx
> +import { Svg, SvgProps } from '..';
Added a new Lock Svg Icon

2023-08-17 05:39 UTC, chanhyeokryptonium commented on packages/react/src/components/Cells/Svg/Icons/Delete.tsx
> +import { Svg, SvgProps } from '..';
new svg Icon

2023-08-17 05:41 UTC, chanhyeokryptonium commented on packages/react/src/components/Cells/ToggleSwitch/index.tsx
> +import styled from 'styled-components';
Added a new Cell - ToggleSwitch

2023-08-17 05:44 UTC, chanhyeokryptonium commented on packages/react/src/components/Tissues/NFTDisplayer/index.tsx
> +  hideBadge?: boolean;
Added a new prop to enable hide/unhide chainbadge

2023-08-17 05:47 UTC, chanhyeokryptonium commented on packages/react/src/hooks/client/useUserClient.ts
> +import { IUser } from '@beoble/js-sdk';
new QueryClient for user

2023-08-17 05:47 UTC, chanhyeokryptonium commented on packages/react/src/theme/Colors.ts
>    mint: '#C1F6CC',
camelCase

2023-08-17 06:02 UTC, chanhyeokryptonium commented on packages/js-sdk/src/core/user.ts
> +    return await this._client.get(Paths.user.web3Snapshot.base, {...params, sort_results: true});
update the params to sync with the changes in the backend

2023-08-17 06:02 UTC, chanhyeokryptonium commented on packages/js-sdk/src/lib/Models/user.ts
> +  chain_type: ChainType;
update schema

2023-08-17 06:05 UTC, chanhyeokryptonium commented on packages/react/src/components/Cells/SelectForm/index.tsx
> +import { ReactElement } from 'react';
added a new Cell - SelectForm (with menu dropdown)
uses react-hook-form + react-select

2023-08-17 06:05 UTC, chanhyeokryptonium commented on packages/react/src/components/Tissues/ItemListCard/index.tsx
> +import { Children } from 'react';
bugfix (display when only title / description is provided)
new param includeDivider

2023-08-17 06:06 UTC, chanhyeokryptonium commented on packages/react/src/components/Tissues/StepperCard/index.tsx
> +import { PropsWithChildren } from 'react';
new Tissue - StepparCard (which displays step, step guide and whatever is needed inside)

2023-08-17 06:09 UTC, chanhyeokryptonium commented on packages/react/src/hooks/mutations/user/usePutUserSettings.ts
> +import { IPutSettings, IUser } from '@beoble/js-sdk';
mutation hook - to update user settings

2023-08-17 06:10 UTC, chanhyeokryptonium commented on packages/react/src/hooks/mutations/user/usePutUserSettings.ts
> +          setUserSettings([optimisticUser]);
this will optimistically update user - 
will revert to the original user state onError state

2023-08-17 06:10 UTC, chanhyeokryptonium commented on packages/react/src/hooks/queries/user/useGetUserByUniqueParam.ts
> +    [QueryKeys.user, queryParamValue, queryParamType],
remove boolean as a part of the key

2023-08-17 09:21 UTC, chanhyeokryptonium commented on packages/beoble/components/FilterSettings/Spam/SettingsSpamFilterMain.tsx
> +        putUserSettings({
optimistic approach

2023-08-17 14:19 UTC, bamnenim-kryptonium requested changes

2023-08-17 14:19 UTC, bamnenim-kryptonium commented on packages/beoble/components/OrganSystems/NFTOwnershipForm/index.tsx
> +                        <Button
you can wrap this Button with styled component too
```typescript
const StyledButton = styled(Button)<{disabled?: boolean}>`
  opacity: ${({disabled}) => disabled ? '50%' : '100%'};
`

<StyledButton disabled={web3Filter.logic === 'OR'} />

```

2023-08-17 14:19 UTC, bamnenim-kryptonium commented on packages/beoble/components/OrganSystems/TokenOwnershipForm/index.tsx
> +            selectOptions={currentTokenOptions}
diff style with the above one?

2023-08-17 14:19 UTC, bamnenim-kryptonium commented on packages/beoble/components/OrganSystems/TokenOwnershipForm/index.tsx
> +                <div>
if you used div to just pass two children as one component, (no style) then use <></> (react fragment)

2023-08-17 14:19 UTC, bamnenim-kryptonium commented on packages/beoble/components/OrganSystems/TokenOwnershipForm/index.tsx
> +          <p>{errors.tokenAmount?.message}</p>
plain pppppppppppp?? let's use <Text/>

2023-08-17 14:19 UTC, bamnenim-kryptonium commented on packages/beoble/components/OrganSystems/TransactionOwnershipForm/index.tsx
> +          <p>{errors.blockChainType?.message}</p>
ppp

2023-08-17 14:19 UTC, bamnenim-kryptonium commented on packages/beoble/components/OrganSystems/TransactionOwnershipForm/index.tsx
> +          <p>{errors.transactionCount?.message}</p>
ppp

2023-08-17 14:19 UTC, bamnenim-kryptonium commented on packages/beoble/components/Organs/Web3FilterSettingCard/index.tsx
> +                    <div
divdiv

2023-08-17 14:19 UTC, bamnenim-kryptonium commented on packages/beoble/helper/arrays.ts
> +  return function (a, b) {
change to arrow function to keep consistency.
type a and b as Array of any

2023-08-17 14:19 UTC, bamnenim-kryptonium commented on packages/beoble/helper/strings.ts
maybe these are better to be in chain helper rather than in string helper/.

2023-08-17 14:28 UTC, chanhyeokryptonium commented on packages/beoble/atoms/spamFilterAtom.ts
> +  TransactionOwnership = 'TransactionOwnership',
THX

2023-08-17 14:29 UTC, chanhyeokryptonium commented on packages/beoble/components/Chatroom/ChatroomEditMainForm.tsx
> +            // if (input_rule) {
OK

2023-08-17 14:46 UTC, chanhyeokryptonium commented on packages/js-sdk/src/lib/Responses/user.ts
> +  native_coin_balance: {
backend gives it this way (probably because there is also another field called "real_balance" which is not being returned atm, but might for the future)

2023-08-17 15:04 UTC, chanhyeokryptonium commented on packages/react/src/hooks/client/useUserClient.ts
> +        if (!prevData) return prevData;
need your confirmation after change

2023-08-18 05:52 UTC, bamnenim-kryptonium requested changes

2023-08-18 05:52 UTC, bamnenim-kryptonium commented on packages/beoble/components/Chatroom/ChatroomEditMainForm.tsx
> +    // toggleIsGlobalLoading(true);
just delete this line

2023-08-18 05:52 UTC, bamnenim-kryptonium commented on packages/beoble/components/OrganSystems/NFTOwnershipForm/index.tsx
> +            selectOptions={availableNftChainTypeOptions.map((option) => ({
ff

2023-08-18 05:52 UTC, bamnenim-kryptonium commented on packages/beoble/components/OrganSystems/TransactionOwnershipForm/index.tsx
> +            selectOptions={availableTxnChainTypeOptions.map((option) => ({
ff

2023-08-18 07:48 UTC, bamnenim-kryptonium approved these changes

2023-08-18 07:52 UTC, merged